### ISSUE TITLE
"cordova-icon-gm: command not found" on OSX Mavericks

### ISSUE THREAD

**Issue by vinelandit** [disusered/cordova-icon-gm#1]
Hi, trying to get this working but even after installing GraphicsMagick (and previously installing Homebrew in order to install GraphicsMagick), then npm installing cordova-icon-gm with the -g flag, the terminal is still saying 'command not found' when I try to run it. Any ideas? Thank you!

**Comment by disusered** [comment]
I goofed on the README, the actual command is `cordova-icon`. Updated, thank you and apologies! 🙈
